### PR TITLE
14 fix scraper cle landmarks

### PR DESCRIPTION
**Pull request by zabrahams**
## Summary

**Issue:** 14

## Checklist

All checks are run in [GitHub Actions](https://github.com/features/actions). You'll be able to see the results of the checks at the bottom of the pull request page after it's been opened, and you can click on any of the specific checks listed to see the output of each step and debug failures.

- [x] Tests are implemented
- [x] All tests are passing
- [x] Style checks run (see [documentation](https://cityscrapers.org/docs/development/) for more details)
- [x] Style checks are passing
- [x] Code comments from template removed

## Questions

Since the meetings are currently on webex for those who are attending and youtube for those who are just viewing I added the youtube link as the address. I wasn't sure if the location object could handle more info about the webex as well, so I didn't add anything, but I could put more in?

### CODE REVIEW

**Comment by skorasaurus** [comment]
thanks so much (and for updating the test!)! 

I ran the scraper; appears to now work as intended and the tests are a-ok now too! 

My only question/concern, which is minor, is that I ran `pipenv run black city_scrapers tests` one more time while in your branch and it made a couple more additional linting fixes (essentially reverting https://github.com/City-Bureau/city-scrapers-cle/pull/31/files#diff-235f4deda53f9ab6fac577ceb19f07c82091d0b4495567532a0c5000a6165793R69 to one line and putting https://github.com/City-Bureau/city-scrapers-cle/pull/31/files#diff-205a4331228f5174b4d06f1f709c16bf08ab8f1c026e44ae276db120e740a50dR93 ; I'm not sure why it wasn't caught by yours, but the additional linting vibes with what black suggestions - https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#how-black-wraps-lines

**Comment by zabrahams** [comment]
Thanks for looking at it! That's super interesting about black - it was actually what split those lines for me. 😂  I kind of figured something like that was going on when I saw the failing check.  I actually had an issue getting the version of black in the pipfile (19.10b0) to run... I ended up having to update it locally to 21.11b1 and I'm guessing that something has changed?  It's weird though I didn't see anything obvious in the changelog and the default line length still seems to be the same? 🤷 I'll try to get it sorted out for the future - and in case anyone else runs into something similar!  I'll get those changes reverted though!

**Comment by skorasaurus** [comment]
either way, I'm not too worried; thanks so much for the PR!

**Comment by skorasaurus** [comment]
(leaving this note for posterity: the checks failed but appears to be an issue with pipenv - ref https://github.com/mhammond/pywin32/issues/1177 )

**Comment by zabrahams** [comment]
@skorasaurus Thanks again!!!!!  I posted about the pywin32 thing on the slack? I don't know if you saw it but I think it's actually breaking the cron/all updates?  From what I could tell the `pywin32==300' dependency was just introduced in the last dependabot mr - and the remaining open ones seem to remove it?  I don't work a ton in python so I'm not sure about the best way to handle it - especially since that issue posted suggests that:
`"pywin32" = {version = "*", sys_platform = "== 'win32'"}`
doesn't help?

**Pull request merged**
