### PR TITLE
Fix spider: cuya_board_control

### PR DESCRIPTION
**Pull request by haileyhoyat**
What's this PR do?
Fixes our Cuyahoga County Board of Control spider (aka. cuya_control_board), which broke due to URL and page structure changes across Cuyahoga County's website.

Why are we doing this?
To ensure our Cuyahoga County Board of Control spider works. The changes in this PR include use of a new class mixin for scraping the Cuyahoga County website.

Steps to manually test
Clone this repo, run the command: cd city_scrapers && scrapy crawl cuya_board_control

Are there any smells or added technical debt to note?
No

### CODE REVIEW

**Comment by skorasaurus** [comment]
fixes #7  =)

**Comment by haileyhoyat** [comment]
Oh FYI:

Will (@skorasaurus ), I don't know if you've heard that City Bureau has a new in-house developer Dan ( @SimmonsRitchie ).

Dan, this is Will, he's the guy who led the initial Cleveland city scrapers build. He works as a web developer for our Cleveland Public Library. 

Will, this is Dan. He's the new in-house City Scrapers developer where he's taking charge of the City Scrapers project. So if you him making changes in the repos don't be alarmed, he's one of us.

**Comment by skorasaurus** [comment]
> Oh FYI:
> 
> Will (@skorasaurus ), I don't know if you've heard that City Bureau has a new in-house developer Dan ( @SimmonsRitchie ).
> 
> Dan, this is Will, he's the guy who led the initial Cleveland city scrapers build. He works as a web developer for our Cleveland Public Library.
> 
> Will, this is Dan. He's the new in-house City Scrapers developer where he's taking charge of the City Scrapers project. So if you him making changes in the repos don't be alarmed, he's one of us.

thanks for all of your contributions so far Dan! @SimmonsRitchie 
@pjsier was the lead architect on the city scrapers and deserves far more credit than I do.

**Comment by SimmonsRitchie** [comment]
Thank you for the intro, @haileyhoyat, and you thank you for the kudos, @skorasaurus! I truly appreciate your own contributions to the city-scrapers project (and of course, to @pjsier too).

**Review by SimmonsRitchie — APPROVED** [review]
This looks good, @haileyhoyat! Code looks clean. Rewritten spider works well. Tests pass. Let's ship it 🚢 🚢🚢

**Pull request merged**
