### PR TITLE
Update cle_city_council.py

### PR DESCRIPTION
**Pull request by haileyhoyat**
hello. @skorasaurus 

added a line to only scrape the meeting if start time (checked for by start=self.legistar_start(event)) does not return as NoneType. 

p.s. i sort of messed up my local environment last night and am not 100% yet if everything is working correctly. please by all means double check that this fix is correct.  

## Summary

**Issue:** #55 

Replace "ISSUE_NUMBER" with the number of your issue so that GitHub will link this pull request with the issue and make review easier.

## Checklist

All checks are run in [GitHub Actions](https://github.com/features/actions). You'll be able to see the results of the checks at the bottom of the pull request page after it's been opened, and you can click on any of the specific checks listed to see the output of each step and debug failures.

- [ ] Tests are implemented
- [ ] All tests are passing
- [ ] Style checks run (see [documentation](https://cityscrapers.org/docs/development/) for more details)
- [ ] Style checks are passing
- [ ] Code comments from template removed

## Questions

Include any questions you have about what you're working on.

### CODE REVIEW

**Comment by skorasaurus** [comment]
thanks for the heads-up; looks good on initial glance but I'll review it more and locally test this on my machine Saturday.

**Comment by haileyhoyat** [comment]
@skorasaurus awesome, thanks so much, Will.

**Review by skorasaurus — CHANGES_REQUESTED** [review]
When I ran the scraper ; I receive an error 
```
  File "/home/myusername/python/city-scrapers-cle/city_scrapers/spiders/cle_city_council.py", line 21, in parse_legistar
    if (self.legistar_start(event) is NoneType):
NameError: name 'NoneType' is not defined"
```
I think at line 21, it should be `None` not `NoneType` . Using None does not produce an error and returns but I cannot see all of the output; so I don't know if those meeting missing the time are still included.

**Comment by haileyhoyat** [comment]
@skorasaurus 

when i run the spider on my machine i get the output of the meetings but get something strange. 

scraper starts out fine with the first entry being a meeting on (12/05/2022). This matches with the City Council Schedule (see first screenshot). 

But then it scrapes the entry for the (11/07/2022) meeting (which is still on track for what city council schedule says), and then jumps to scraping the meeting for (12/21/2021) (see second screenshot). This is interesting because the meeting that should come after the (11/07/2022) meeting is the (10/31/2022) meeting which is the meeting with the missing time entry. Something is really throwing the spider off. 

Thoughts?

Screen Shot 2022-10-22 at 7 06 22 PM

Screen Shot 2022-10-22 at 7 18 10 PM

**Comment by haileyhoyat** [comment]
@skorasaurus 

omg, ok i think i solved it (sort of). 

admittedly slightly hippie-dippy way of fixing this but tbh at this point i just want this bug to be over with.

if self.legistar_start(event) is None, then make the start a passed time that will register the meeting on the Documenters.org website as 'passed' (i.e. a meeting that is already passed and shouldn't be assigned).

and i am getting the meetings now (i.e. scraper not skipping to 2021 - still don't know why it was doing that). 

Screen Shot 2022-10-22 at 8 03 25 PM

**Comment by LienDang** [comment]
Hi @haileyhoyat From the [attached image](https://user-images.githubusercontent.com/25486536/197365828-658f754e-46bc-4aa0-b31a-b6281cdfd91d.png) I can see that there is actually no meeting on 10/31/2022. It says `There will not be a Cleveland City Council Meeting on October 31, 2022.`. So I guess that's why that row missed the time info. So in this case, I guess it's best to skip the row and not try to convert it to a Meeting. Here's how I would handle the case
```python
start = self.legistar_start(event)
if start:
    meeting = Meeting(
        title=event["Name"]["label"],
        description=self._parse_description(event),
        classification=self._parse_classification(event),
        start=start,
        end=None,
        all_day=False,
        time_notes="",
        location=self._parse_location(event),
        links=self.legistar_links(event),
        source=self.legistar_source(event),
    )

    meeting["status"] = self._get_status(meeting)
    meeting["id"] = self._get_id(meeting)
    
    yield meeting
```
Can you try that solution?
Also, can you please make sure the PR is passed before requesting code review. Thanks!

**Comment by haileyhoyat** [comment]
@LienDang Hi. Thank you for the guidance. I have implemented your solution, as well as black/flake8/isort. 

i think the reason my tests fail is because i don't use venv on my local machine. i am getting the correct meetings, it is skipping over the (10/31/2022) meeting, and black/flake8/isort are passing.

Any advice on how to proceed?

Screen Shot 2022-10-25 at 11 00 42 AM

Screen Shot 2022-10-25 at 11 02 12 AM

**Comment by skorasaurus** [comment]
@LienDang thank you for the extra assist; @haileyhoyat thank you for your work on this;confirmed that the scraper skips the 31st meeting and continues to successfully scrape for november.

**Comment by haileyhoyat** [comment]
@LienDang @skorasaurus thank you both so much - super grateful, the Cleveland team will be very happy.

**Comment by skorasaurus** [comment]
Regarding the failure: 
I'm really curious why packages from python 3.8 would be loaded at this [part in the job ](https://github.com/City-Bureau/city-scrapers-cle/actions/runs/3321983956/jobs/5490377904#step:6:100) when this is for python 3.6. 
(I have no idea whether this is a bad thing; this is just a hunch).

**Comment by haileyhoyat** [comment]
@skorasaurus i always get stuck on that one in the CI, and unfortunately no other CI tests can run after that failure.

**Pull request merged**
